apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: gatekeeper-operator-controller-manager
  name: gatekeeper-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: gatekeeper-operator-controller-manager
status:
  loadBalancer: {}
