apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  image:
    image: docker.io/openpolicyagent/gatekeeper:v3.3.0
  audit:
    replicas: 1
    logLevel: INFO
    emitAuditEvents: Enabled
  validatingWebhook: Enabled
  mutatingWebhook: Enabled
  webhook:
    replicas: 3
    logLevel: INFO
    emitAdmissionEvents: Enabled
