apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    replicas: 1
    logLevel: INFO
    emitAuditEvents: Enabled
  validatingWebhook: Enabled
  mutatingWebhook: Enabled
  webhook:
    replicas: 3
    logLevel: INFO
    emitAdmissionEvents: Enabled
    disabledBuiltins:
      - http.send
