name: OLM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Create and set up K8s KinD Cluster
      run: |
        ./scripts/kind-with-registry.sh
        make deploy-olm

    - name: Build and Push Test Container Image and Bundle/Bundle Index Images
      run: |
        OPERATOR_VERSION=$(awk '/^VERSION/ {print $3}' Makefile)
        make build-and-push-bundle-images IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA REPO=localhost:5000 VERSION=$GITHUB_SHA OPERATOR_VERSION=${OPERATOR_VERSION}

    - name: Deploy resources on KIND cluster to install Gatekeeper
      run: |
        make deploy-with-olm REPO=localhost:5000 VERSION=$GITHUB_SHA NAMESPACE=mygatekeeper

    - name: E2E Tests
      run: |
        make test-e2e
        kubectl delete --wait namespace mygatekeeper
